# Generated by Django 4.1 on 2022-08-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_product_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
