# Generated by Django 4.1 on 2022-08-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='recipie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('desc', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
    ]
