# Generated by Django 4.1 on 2022-08-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_recipie_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipie',
            name='desc',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
