# Generated by Django 4.1 on 2022-09-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_totalorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderid',
            field=models.IntegerField(default=0),
        ),
    ]
